### ISSUE TITLE
Error when adding a new item 

### ISSUE THREAD

**Issue by RedWolves** [AutomatedTester/node-pomodoro#4]
```
$ npm install -g pomodoro
/usr/local/bin/pomodoro -> /usr/local/lib/node_modules/pomodoro/bin/main.js
/usr/local/bin/p -> /usr/local/lib/node_modules/pomodoro/bin/main.js
/usr/local/lib
└─┬ pomodoro@0.2.0 
  ├── colors@1.0.3 
  ├── growl@1.8.1 
  ├─┬ nomnom@1.8.1 
  │ ├─┬ chalk@0.4.0 
  │ │ ├── ansi-styles@1.0.0 
  │ │ ├── has-color@0.1.7 
  │ │ └── strip-ansi@0.1.1 
  │ └── underscore@1.6.0 
  └── single-line-log@0.4.1 

~
$ pomodoro -h

Usage: /usr/local/bin/node pomodoro [task] [options]

task     This is the task you are going to do. When the pomodoro iscomplete it will say the time is done on that task

Options:
   -a, --add       Add a new item that can be processed later
   -r, --remove    Remove items that we have saved to disk
   -s, --show      Show all the items in the file
   --start         Start running the top item in the list
   -b, --break     Time a break and be notified when to start again. Pass in the amount of munites to break for.
   -v, --version   writes the version to the screen

~
$ pomodoro -s
~
$ pomodoro -a "A new item to add"
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at /usr/local/lib/node_modules/pomodoro/lib/pomodoro.js:92:22
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

**Comment by markphd** [comment]
In `pomodoro.js` the object `items` throws undefined when doing `JSON.parse(data)` at line 92. 
I "somehow" fixed it by surrounding quotes in each object keys.
```
var items = {"todo": [], "completed":[]};
```

Is this an acceptable solution? 👍  || 👎

**Comment by AutomatedTester** [comment]
I have published a new version
