### ISSUE TITLE
Error when starting pomodoro

### ISSUE THREAD

**Issue by RedWolves** [AutomatedTester/node-pomodoro#5]
```
pomodoro --start
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at /usr/local/lib/node_modules/pomodoro/lib/pomodoro.js:119:24
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

**Comment by AutomatedTester** [comment]
I have just released a new version and can't see to recreate this issue. If it still fails, can you help debug what the issue is and then we can reopen.
